### ISSUE TITLE
Investigate panic in peerlist

### ISSUE THREAD

**Issue by robskillington** [uber/tchannel-go#614] opened 2017-03-22 14:54 UTC
Using v1.2.2 we encountered a concurrent map read/write panic in production.  After briefly looking at the code it seems protected so there must be something interesting going on.  Seen this definitely at least once, will keep an eye out for another occurrence.

```
fatal error: concurrent map read and map write

goroutine 257088 [running]:
runtime.throw(0xdf9e52, 0x21)
        /usr/lib/go-1.7/src/runtime/panic.go:566 +0x95 fp=0xc9c39c49b8 sp=0xc9c39c4998
runtime.mapaccess2_faststr(0xcb70c0, 0xde0ab5, 0xc48148000000c024, 0x718d48c3000000c8, 0x6839cd, 0xc9bf6a1cc0)
        /usr/lib/go-1.7/src/runtime/hashmap_fast.go:306 +0x52b fp=0xc9c39c4a18 sp=0xc9c39c49b8
code.uber.internal/infra/statsdex/vendor/github.com/uber/tchannel-go.(*PeerList).exists(0xc9c15a5b90, 0xc48148000000c024, 0x718d48c3000000c8, 0xc9bf6a1cb0, 0x0, 0x683959)
        /var/cache/udeploy/r/statsdex_m3dbnode/dca1-produ-0000000010-v2/tmp/src/code.uber.internal/infra/statsdex/vendor/github.com/uber/tchannel-go/peer.go:215 +0x63 fp=0xc9c39c4a70 sp=0xc9c39c4a18
code.uber.internal/infra/statsdex/vendor/github.com/uber/tchannel-go.(*PeerList).updatePeer(0xc9c15a5b90, 0x62e114)
        /var/cache/udeploy/r/statsdex_m3dbnode/dca1-produ-0000000010-v2/tmp/src/code.uber.internal/infra/statsdex/vendor/github.com/uber/tchannel-go/peer.go:227 +0x46 fp=0xc9c39c4ac8 sp=0xc9c39c4a70
code.uber.internal/infra/statsdex/vendor/github.com/uber/tchannel-go.(*subChannelMap).updatePeer(0xc9c39c4c28, 0x62e114)
        /var/cache/udeploy/r/statsdex_m3dbnode/dca1-produ-0000000010-v2/tmp/src/code.uber.internal/infra/statsdex/vendor/github.com/uber/tchannel-go/subchannel.go:215 +0xe4 fp=0xc9c39c4b58 sp=0xc9c39c4ac8
created by code.uber.internal/infra/statsdex/vendor/github.com/uber/tchannel-go.(*Channel).newConnection
        /var/cache/udeploy/r/statsdex_m3dbnode/dca1-produ-0000000010-v2/tmp/src/code.uber.internal/infra/statsdex/vendor/github.com/uber/tchannel-go/connection.go:324 +0x9b0
```

cc @junchaowu @alxn @akshayjshah @prashantv

**Comment by prashantv** [comment] 2017-03-22 15:42
That's really interesting -- like you said, all the code that accesses `peersByHostPort` seems to be protected correctly, and there's no access to `peersByHostPort` outside of `peer.go`.

There's also something a little odd about the stacktrace you posted -- normally panics will print the whole stack trace for that goroutine, or if it's a partial dump, they will print `additional frames elided`:
```
main.f(0x62)
	/home/prashant/panic.go:12 +0x37
...additional frames elided...
```

In this case, the bottom of the stacktrace shows:
```
code.uber.internal/infra/statsdex/vendor/github.com/uber/tchannel-go.(*subChannelMap).updatePeer(0xc9c39c4c28, 0x62e114)
        [...]code.uber.internal/infra/statsdex/vendor/github.com/uber/tchannel-go/subchannel.go:215 +0xe4 fp=0xc9c39c4b58 sp=0xc9c39c4ac8
created by code.uber.internal/infra/statsdex/vendor/github.com/uber/tchannel-go.(*Channel).newConnection
        [...]code.uber.internal/infra/statsdex/vendor/github.com/uber/tchannel-go/connection.go:324 +0x9b0
```

(no eliding of frames)

However, `newConnection` creates a goroutine for `readFrames`, not for the `updatePeer` call. The `(*subChannelMap).updatePeer` function is only called from `(*Channel).updatePeer`, which can be called from a few different functions. However, none of these stack frames are showing up.

**Comment by prashantv** [comment] 2017-03-22 16:06
Another odd thing about that stack, looking at the code for `*subChannelMap.updatePeer`:
```go
func (subChMap *subChannelMap) updatePeer(p *Peer) {
  subChMap.RLock()
  for _, subCh := range subChMap.subchannels {
    if subCh.Isolated() {
      subCh.RLock()
      subCh.Peers().updatePeer(p)
      subCh.RUnlock()
    }
  }
  subChMap.RUnlock()
}
```

`updatePeer` is only called if the subchannel is isolated. Isolated subchannels are pretty rarely used. It doesn't seem like anything in statsdex is creating an isolated subchannel (requires using the [`Isolated`](https://godoc.org/github.com/uber/tchannel-go#Isolated) function, which I see no references to in the codebase.

@robskillington Do you know if there's anything in the codebase using `Isolated`?

**Comment by robskillington** [comment] 2017-03-22 19:31
Yeah we don't really have any calls to Isolated or anything like that.  Our current client construct method is this:
```go
func newConn(channelName string, address string, opts Options) (xclose.SimpleCloser, rpc.TChanNode, error) {
	channel, err := tchannel.NewChannel(channelName, opts.ChannelOptions())
	if err != nil {
		return nil, nil, err
	}
	endpoint := &thrift.ClientOptions{HostPort: address}
	thriftClient := thrift.NewClient(channel, nchannel.ChannelName, endpoint)
	client := rpc.NewTChanNodeClient(thriftClient)
	return channel, client, nil
}
```

And our channel options:
```go
	tchannelOpts := &tchannel.ChannelOptions{
		Logger: xm3dblog.NewNoopLogger(),
	}
```

**Comment by prashantv** [comment] 2017-03-23 17:35
Given the truncated stack trace, and the fact that `updatePeer` is being called when I wouldn't expect it to (since there's no isolated subchannels), this seems like something outside of tchannel, maybe some memory corruption?

**Comment by prashantv** [comment] 2017-04-07 00:25
Closing due to lack of repro -- this doesn't seem like a TChannel issue looking at the code.

Feel free to reopen if you see the issue again, would be great if we could figure out how to reproduce it.

**Closed by prashantv** 2017-04-07 00:25 UTC
