### ISSUE TITLE
Upload releases of Apache Thrift 0.9.3 and 0.10.0

### ISSUE THREAD

**Issue by peter-edge** [uber/tchannel-go#610] opened 2017-03-20 10:54 UTC
Filing this as a reminder :)

**Comment by prashantv** [comment] 2017-03-20 16:04
Thanks for the reminder, I've uploaded the Linux and Darwin x64 releases here:
https://github.com/prashantv/thrift/releases/tag/p0.0.1

**Comment by peter-edge** [comment] 2017-03-20 16:07
Hey, specifically:

What version is this for? I was going to ask you to name this to what version it is, and I still don't know :)

**Comment by peter-edge** [comment] 2017-03-20 16:07
Ie I think the release should be named 0.9.3 or 0.10.0, not p0.0.1 (probably also not on a personal repo, rather under uber or uber-go, but alas).

**Comment by peter-edge** [comment] 2017-03-20 16:23
OK, let me close this next time, this isn't fixed yet, let me confirm:

What do I base off of for glide? There is no information on what users should lock to, the given link doesn't seem to link to an apache thrift commit.

**Comment by prashantv** [comment] 2017-03-20 16:31
Given the issue was about "upload releases for Thrift" -- I figured that part was done in the release I linked. It has exact information about what commit of Thrift we used to build the release.

In terms of library compatibility, that's a separate issue since Apache Thrift has not done a good job of giving us releases we can pin to (they've made breaking changes within a patch).

The commit hashes in the release will work, but I don't know if there's a tag range that will work -- I think you're the one with the most context for what is the latest version of Thrift that will work without changing the API.

**Comment by peter-edge** [comment] 2017-03-20 16:32
The whole bug stemmed from the need for:

- A thrift compiler version to lock to (this is what is provided above)
- A corresponding commit to github.com/apache/thrift that golang users should set as their glide version (this is what we dont have)

I need the latter, this is how this bug was made (the lack of the latter).

**Comment by prashantv** [comment] 2017-03-20 16:37
Yes, this issue was specifically about uploading the release. I think the commit pinning is a good question, but more related to (#608). If both the issues are the same, let's close one as a duplicate of the other.

I'd suggest users pin to the last commit before the set generation was modified to avoid using `bool` values in maps. I wasn't aware of that change till you brought it up, so I figured you'd be the best person to answer that question.

**Closed** 2017-03-20 16:41 UTC
Labels: thrift-gen
